// doc_id: doc_other_0009 — generated by generate-tab-childpanels.js (M33)
//
// GachaDs3LegendaryChild — UCUF ChildPanel for tab "Legendary".
// Wire this into the CompositePanel's _switchToTab routing table.

import { ChildPanelBase } from '../../core/ChildPanelBase';
import type { UISkinResolver } from '../../core/UISkinResolver';
import type { UITemplateBinder } from '../../core/UITemplateBinder';
import { UCUFLogger, LogCategory } from '../../core/UCUFLogger';

export class GachaDs3LegendaryChild extends ChildPanelBase {
    override dataSource = 'config';
    private static readonly ROOT_PATH = 'TabLegendaryContent';

    public override onMount(binder: UITemplateBinder, _skin: UISkinResolver): void {
        UCUFLogger.info(LogCategory.LIFECYCLE, '[GachaDs3LegendaryChild] onMount', { rootPath: GachaDs3LegendaryChild.ROOT_PATH });
        // TODO: cache Label / Sprite refs from binder under TabLegendaryContent
        void binder;
    }

    public override onDataChanged(_data: unknown): void {
        // TODO: bind data to cached refs.
    }

    public override onUnmount(): void {
        // TODO: release refs.
    }
}
