// doc_id: doc_other_0009 — generated by generate-tab-childpanels.js (M33)
//
// GachaDs3SupportChild — UCUF ChildPanel for tab "Support".
// Wire this into the CompositePanel's _switchToTab routing table.

import { ChildPanelBase } from '../../core/ChildPanelBase';
import type { UISkinResolver } from '../../core/UISkinResolver';
import type { UITemplateBinder } from '../../core/UITemplateBinder';
import { UCUFLogger, LogCategory } from '../../../core/utils/UCUFLogger';

export class GachaDs3SupportChild extends ChildPanelBase {
    override dataSource = 'config';
    private static readonly ROOT_PATH = 'TabSupportContent';

    public override onMount(binder: UITemplateBinder, _skin: UISkinResolver): void {
        UCUFLogger.info(LogCategory.LIFECYCLE, '[GachaDs3SupportChild] onMount', { rootPath: GachaDs3SupportChild.ROOT_PATH });
        // TODO: cache Label / Sprite refs from binder under TabSupportContent
        void binder;
    }

    public override onDataChanged(_data: unknown): void {
        // TODO: bind data to cached refs.
    }

    public override onUnmount(): void {
        // TODO: release refs.
    }
}
